#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

# wp director is expected to be bind mount, mk here for local test runs
mkdir -p /var/www/html/wp

if [ -f /var/www/html/wp/wp-config.php ]; then
  cp /wp-config.php /var/www/html/wp-config.php
  chown www-data:www-data /var/www/html/wp-config.php
fi

# retain standard wp-content
rsync -a /var/www/html/wp-content /var/www/html/wp

# ensure proper permissions
find /var/www/html/wp -type d -exec chmod 755 {} \;
find /var/www/html/wp -type f -exec chmod 644 {} \;

# ensure www-data ownership
chown -R www-data:www-data /var/www/html

exec 2>&1
exec nginx -g "daemon off;"
